// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: protocol/telemetry.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	SendMetrics(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_SendMetricsClient, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) SendMetrics(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_SendMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], "/protocol.TelemetryService/SendMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceSendMetricsClient{stream}
	return x, nil
}

type TelemetryService_SendMetricsClient interface {
	Send(*Metric) error
	CloseAndRecv() (*Result, error)
	grpc.ClientStream
}

type telemetryServiceSendMetricsClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceSendMetricsClient) Send(m *Metric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *telemetryServiceSendMetricsClient) CloseAndRecv() (*Result, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	SendMetrics(TelemetryService_SendMetricsServer) error
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) SendMetrics(TelemetryService_SendMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMetrics not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_SendMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).SendMetrics(&telemetryServiceSendMetricsServer{stream})
}

type TelemetryService_SendMetricsServer interface {
	SendAndClose(*Result) error
	Recv() (*Metric, error)
	grpc.ServerStream
}

type telemetryServiceSendMetricsServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceSendMetricsServer) SendAndClose(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *telemetryServiceSendMetricsServer) Recv() (*Metric, error) {
	m := new(Metric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMetrics",
			Handler:       _TelemetryService_SendMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protocol/telemetry.proto",
}
